//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audiamus.aaxconv.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("audiamus.aaxconv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap added {
            get {
                object obj = ResourceManager.GetObject("added", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Audio48 {
            get {
                object obj = ResourceManager.GetObject("Audio48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string CptHide {
            get {
                return ResourceManager.GetString("CptHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string CptShow {
            get {
                return ResourceManager.GetString("CptShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible files (*.aax)|*.aax|Audible files (*.aa)|*.aa|All Audible files (*.aax; *.aa)| *.aax; *.aa.
        /// </summary>
        internal static string FilterAudibleFiles {
            get {
                return ResourceManager.GetString("FilterAudibleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files (*.exe)|*.exe.
        /// </summary>
        internal static string FilterExeFiles {
            get {
                return ResourceManager.GetString("FilterExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string HdrAuthor {
            get {
                return ResourceManager.GetString("HdrAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit rate.
        /// </summary>
        internal static string HdrBitRate {
            get {
                return ResourceManager.GetString("HdrBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string HdrCopyright {
            get {
                return ResourceManager.GetString("HdrCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string HdrDuration {
            get {
                return ResourceManager.GetString("HdrDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string HdrGenre {
            get {
                return ResourceManager.GetString("HdrGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrator.
        /// </summary>
        internal static string HdrNarrator {
            get {
                return ResourceManager.GetString("HdrNarrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string HdrPublisher {
            get {
                return ResourceManager.GetString("HdrPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Rate.
        /// </summary>
        internal static string HdrSampleRate {
            get {
                return ResourceManager.GetString("HdrSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string HdrSize {
            get {
                return ResourceManager.GetString("HdrSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string HdrTitle {
            get {
                return ResourceManager.GetString("HdrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing year.
        /// </summary>
        internal static string HdrYear {
            get {
                return ResourceManager.GetString("HdrYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string MsgAborted {
            get {
                return ResourceManager.GetString("MsgAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom activation code has been removed..
        /// </summary>
        internal static string MsgActivationCodeRemoved {
            get {
                return ResourceManager.GetString("MsgActivationCodeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation error for.
        /// </summary>
        internal static string MsgActivationError1 {
            get {
                return ResourceManager.GetString("MsgActivationError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a different activation code?.
        /// </summary>
        internal static string MsgActivationError2 {
            get {
                return ResourceManager.GetString("MsgActivationError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be skipped..
        /// </summary>
        internal static string MsgActivationError3 {
            get {
                return ResourceManager.GetString("MsgActivationError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done.
        /// </summary>
        internal static string MsgAllDone {
            get {
                return ResourceManager.GetString("MsgAllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All modifications to settings will be lost!
        ///
        ///Are you sure?.
        /// </summary>
        internal static string MsgAllModifLost {
            get {
                return ResourceManager.GetString("MsgAllModifLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common root folder for all books.
        /// </summary>
        internal static string MsgCommonRootFolder {
            get {
                return ResourceManager.GetString("MsgCommonRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to converted.
        /// </summary>
        internal static string MsgConverted {
            get {
                return ResourceManager.GetString("MsgConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exists and is not empty.
        ///Override content, new folder or skip book?
        ///[Yes]: Override content
        ///[No]: New folder
        ///[Cancel]: Skip book.
        /// </summary>
        internal static string MsgDirectoryCreationCallback {
            get {
                return ResourceManager.GetString("MsgDirectoryCreationCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been tested 
        ///against FFmpeg version.
        /// </summary>
        internal static string MsgFFmpegVersion1 {
            get {
                return ResourceManager.GetString("MsgFFmpegVersion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The located version is.
        /// </summary>
        internal static string MsgFFmpegVersion2 {
            get {
                return ResourceManager.GetString("MsgFFmpegVersion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try with this version.
        /// </summary>
        internal static string MsgFFmpegVersion3 {
            get {
                return ResourceManager.GetString("MsgFFmpegVersion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can always be altered in the basic settings, 
        ///via the system menu.
        /// </summary>
        internal static string MsgFFmpegVersion4 {
            get {
                return ResourceManager.GetString("MsgFFmpegVersion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate .aax and .aa files with.
        /// </summary>
        internal static string MsgFileAssoc {
            get {
                return ResourceManager.GetString("MsgFileAssoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has to be restarted for the 
        ///new language setting to take effect.
        ///
        ///Restart now?.
        /// </summary>
        internal static string MsgLangRestart {
            get {
                return ResourceManager.GetString("MsgLangRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location and verification successful.
        /// </summary>
        internal static string MsgLocationVerifSucc {
            get {
                return ResourceManager.GetString("MsgLocationVerifSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The code provided can only be
        ///verified when converting an .aax file.
        /// </summary>
        internal static string MsgNoteActivationCode {
            get {
                return ResourceManager.GetString("MsgNoteActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of AaxAudioConverter is avaliable.
        ///Download now?.
        /// </summary>
        internal static string MsgOnlineUpdateDownload {
            get {
                return ResourceManager.GetString("MsgOnlineUpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of AaxAudioConverter is ready for installation..
        /// </summary>
        internal static string MsgOnlineUpdateInstall {
            get {
                return ResourceManager.GetString("MsgOnlineUpdateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install now?.
        /// </summary>
        internal static string MsgOnlineUpdateInstallLater {
            get {
                return ResourceManager.GetString("MsgOnlineUpdateInstallLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install now? (Will close cuirrent AaxAudioConverter window.).
        /// </summary>
        internal static string MsgOnlineUpdateInstallNow {
            get {
                return ResourceManager.GetString("MsgOnlineUpdateInstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string MsgOnlineUpdateNewVersion {
            get {
                return ResourceManager.GetString("MsgOnlineUpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes for last file!
        ///
        ///[Yes]: Save changes before switching to the new file.
        ///[No]: Discard last file changes, just switch to the new file.
        ///[Cancel]: Cancel new file..
        /// </summary>
        internal static string MsgPreviewUnsavedChanges {
            get {
                return ResourceManager.GetString("MsgPreviewUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch.
        /// </summary>
        internal static string MsgProgCh {
            get {
                return ResourceManager.GetString("MsgProgCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        internal static string MsgProgPt {
            get {
                return ResourceManager.GetString("MsgProgPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string MsgProgStep {
            get {
                return ResourceManager.GetString("MsgProgStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        internal static string MsgProgTr {
            get {
                return ResourceManager.GetString("MsgProgTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected custom genres?.
        /// </summary>
        internal static string MsgRemoveGenres {
            get {
                return ResourceManager.GetString("MsgRemoveGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected files from list?.
        /// </summary>
        internal static string MsgRemSelFiles {
            get {
                return ResourceManager.GetString("MsgRemSelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings – here and on the
        ///main dialog – to default values?.
        /// </summary>
        internal static string MsgResetAllSettings {
            get {
                return ResourceManager.GetString("MsgResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some done.
        /// </summary>
        internal static string MsgSomeDone {
            get {
                return ResourceManager.GetString("MsgSomeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part; Teil.
        /// </summary>
        internal static string PartNames {
            get {
                return ResourceManager.GetString("PartNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has customization.
        /// </summary>
        internal static string StsHasCustomization {
            get {
                return ResourceManager.GetString("StsHasCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customization.
        /// </summary>
        internal static string StsNoCustomization {
            get {
                return ResourceManager.GetString("StsNoCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization removed, [OK] to apply..
        /// </summary>
        internal static string StsNoCustomizationOk {
            get {
                return ResourceManager.GetString("StsNoCustomizationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About….
        /// </summary>
        internal static string SysMenuItemAbout {
            get {
                return ResourceManager.GetString("SysMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string SysMenuItemHelp {
            get {
                return ResourceManager.GetString("SysMenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic &amp;Settings….
        /// </summary>
        internal static string SysMenuItemSettings {
            get {
                return ResourceManager.GetString("SysMenuItemSettings", resourceCulture);
            }
        }
    }
}
